issue_tracker/authentication/urls.py
from django.contrib import admin
from django.urls import path,include
from issue_tracker.views import home
from . import views
urlpatterns = [
    
    path('',views.home.as_view()),
    path('signin',views.signin.as_view(),name="signin"),
    path('signup',views.SignupView.as_view(),name="signup"),
    path('signout',views.signin.as_view(),name="signout"),
    path("dashboard",views.DashBoardView.as_view(),name="dashboard"),
    path("dashboard/<str:filter_param>/",views.DashBoardView.as_view(),name="filter"),
    path("profile",views.ProfileView.as_view(),name="view_profile"),
    path("edit",views.EditProfileView.as_view(),name="edit_profile")
]

issue_tracker/issue_tracker/urls.py
from django.contrib import admin
from django.urls import path,include
from issue_tracker.views import home
from authentication import views

urlpatterns = [
    path('',include(('authentication.urls','authentication'),namespace="authentication")),
    path('users',include('users.urls')),
    path('projects/',include(('projects.urls','projects'),namespace="projects")),
    path("stories/", include(("stories.urls", "stories"), namespace="stories")),
]

issue_tracker/projects/urls.py
from django.contrib import admin
from django.urls import path,include
from users.models import User
from projects.views import home,ProjectsViewSet,ProjectEditView



urlpatterns = [
    path('',home.as_view()),
    path('api/project',ProjectsViewSet.as_view()),
    path("project_edit/<int:project_id>/",ProjectEditView.as_view(),
        name="project_edit",)
]

issue_tracker/stories/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import CreateStoryView
from authentication import views
from rest_framework import routers
from stories.views import CreateStoryView,ViewStory,UpdateStory,StoryDeleteView



urlpatterns = [
    path( "create/<int:project_id>/", CreateStoryView.as_view(),name="create_story",),
    path("show/<int:project_id>/", ViewStory.as_view(), name="stories_list"),
    path("update/<int:project_id>/<int:story_id>/",UpdateStory.as_view(),
    name="update_story",
    ),
     path("delete/<int:project_id>/<int:story_id>/",StoryDeleteView.as_view(),
        name="delete_story",
    )
]

issue_tracker/users/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework import routers
from users.views import MembersViewSet
from . import views

router=routers.DefaultRouter()
router.register(r'users',MembersViewSet)
urlpatterns = [

    path('',include(router.urls)),

]

issue_tracker/stories/models.py
from django.db import models
from users.models import User
# Create your models here.

class Story(models.Model):
        STATUS_CHOICES = (
        (1, "Not Started"),
        (2, "Started"),
        (3, "Finished"),
        (4, "Delivered"),
        )

        SCHEDULE_CHOICES = (
        (1, "Scheduled"),
        (2, "Not Scheduled"),
        )
        
        title=models.CharField(max_length=100,null=False)
        is_scheduled=models.IntegerField(choices=SCHEDULE_CHOICES,default=2)
        description=models.TextField()
        status=models.IntegerField(choices=STATUS_CHOICES,default=1)
        project=models.ForeignKey("projects.Project",null=False, on_delete=models.CASCADE)
        assignee=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
        estimated_time=models.IntegerField()
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)
        is_deleted= models.BooleanField(default=False)

issue_tracker/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import UserManager
from datetime import date
# Create your models here.


class User(AbstractUser):
    username=None
    password=models.CharField(null=False)
    email=models.EmailField(null=False,unique=True)
    first_name=models.CharField(max_length=50,null=False)
    last_name=models.CharField(max_length=50,null=False)
    dob = models.DateField(default=date.today)
    USERNAME_FIELD='email'
    objects=UserManager()
    REQUIRED_FIELDS=[]
    # projects=models.ManyToManyField(Project)

issue_tracker/stories/views.py
from django.shortcuts import render,redirect
from stories.models import Story
from users.serializers import UserSerializer
from django.contrib import messages
from django.views import View
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from projects.models import Project,ProjectTag
from stories.serializers import StorySerializer
from users.models import User
from django.conf import settings
from django.core.mail import send_mail


class CreateStoryView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/add_story.html"
    login_url = "signin"

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        project_id=self.kwargs["project_id"]
        print(project_id)
        project=Project.objects.get(id=project_id)  

        if(self.request.user in project.members.all() 
        or self.request.user == project.owner):
            users=project.members.all()
        else:
            users=None
        
        context["project"]=project
        context["users"]=users
          
        return context
    
    
    def post(self, request, project_id):
        project = Project.objects.get(id=project_id)
        data = {
            "title": request.POST.get("title"),
            "description": request.POST.get("description"),
            "assignee": request.POST.get("assignee"),
            "estimated_time": request.POST.get("estimate"),
            "project": project_id,
        }
        serializer = StorySerializer(data=data)

        if serializer.is_valid():
            serializer.save()
            messages.success(request, "Story has been successfully created")
            assignee_id = request.POST.get("assignee")
            assignee = User.objects.get(id=assignee_id)

            subject = 'Assigned to a new story'
            message = f"You've been assigned to the story '{serializer.data['title']}' in {project.title}."
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [assignee.email]
            send_mail( subject, message, email_from, recipient_list )
            return redirect("authentication:dashboard")
        else:
            context = self.get_context_data()
            context["serializer_errors"] = serializer.errors
            return self.render_to_response(context)

class ViewStory(LoginRequiredMixin, TemplateView):
     template_name = "dashboard/story_view.html"
     login_url = "signin"

     def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs["project_id"]
        project = Project.objects.get(id=project_id)
        scheduled_stories = Story.objects.filter(project=project, is_scheduled=1
        , is_deleted=False).order_by("-status", "created_at")
        unscheduled_stories = Story.objects.filter(project=project, is_scheduled=2
       , is_deleted=False ).order_by("-status", "created_at")
        context["project"] = project
        context["scheduled_stories"] = scheduled_stories
        context["unscheduled_stories"] = unscheduled_stories
        return context


class UpdateStory(LoginRequiredMixin, TemplateView):
        template_name = "dashboard/update_story.html"
        login_url = "signin"

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            project_id = self.kwargs["project_id"]
            story_id = self.kwargs["story_id"]
            project = Project.objects.get(id=project_id)
            story = Story.objects.get(id=story_id, project_id=project_id)

            if (
                self.request.user in project.members.all()
                or self.request.user == project.owner
            ):
                users = project.members.all()
            else:
                users = None
            
            context["project"] = project
            context["story"] = story
            context["users"] = users
            context["status_choices"] = Story.STATUS_CHOICES
            context["schedule_choices"] = Story.SCHEDULE_CHOICES
            return context

        def post(self, request, project_id, story_id):
            story = Story.objects.get(id=story_id)

            if story.status == 4:
                messages.error(request, "Delivered stories cannot be updated.")
                return self.get(request, project_id=project_id, story_id=story_id)

            if story.status in [2, 3] and request.POST.get("is_scheduled") == "2":
                messages.error(request, "Started/Finished stories cannot be unscheduled.")
                return self.get(request, project_id=project_id, story_id=story_id)

            if request.POST.get("is_scheduled") == "2" and story.status != 1:
                messages.error(
                    request,
                    "To unschedule a story, its state should be set to Not Started first.",
                )
                return self.get(request, project_id=project_id, story_id=story_id)

            serializer = StorySerializer(story, data=request.POST, partial=True)
            if serializer.is_valid():
                serializer.save()
                messages.success(request, "Story has been updated successfully")
                return redirect("stories:stories_list", project_id=project_id)
            else:
                context = self.get_context_data()
                context["serializer_errors"] = serializer.errors
                return self.render_to_response(context)


class StoryDeleteView(LoginRequiredMixin, View):
    
    login_url="signin"
    def post(self, request, project_id, story_id):
        story = Story.objects.get(id=story_id)
        story.is_deleted = True
        story.save()

        messages.success(request, "Story has been soft deleted")
        return redirect("stories:stories_list", project_id=project_id)


       

issue_tracker/users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rest_framework import viewsets
from users.models import User
from users.serializers import UserSerializer
from django.contrib import messages





class MembersViewSet(viewsets.ModelViewSet):
    queryset=User.objects.all()
    serializer_class=UserSerializer

issue_tracker/templates/dashboard/add_story.html
{% extends "dashboard/navigation.html" %}
{% block body %}

{% if users %}
<form action="{% url 'stories:create_story' project_id=project.id %}" method="POST">
    {% csrf_token %}
    <label for="">Title</label>
    <input type="text" id="title" name="title" placeholder="Write title of the project" required>
    <br>

    <label for="">Description</label>
    <input type="text" id="description" name="description" placeholder="Write your description of the project" required>
    <br>
    <br>
    <select id="assignee" name="assignee">
        {% for user in users %}
        <option value="{{ user.id }}">{{ user.first_name }}</option>
        {% endfor %}
    </select>
    <br>
    <br>
    <label for="">Estimate(in hrs)</label>
    <input type="text" id="estimate" name="estimate" placeholder="Write estimated time taken" required>
    <br>
    <button type="submit">Create Story</button>
</form>
{% else %}
<p>You have no authority in this project.Contact the manager or owner!</p>
{% endif %}

{% endblock %}

issue_tracker/templates/dashboard/create_projects.html
{% extends "dashboard/navigation.html" %}
{% load static %}



{% block body %}


    <form action="api/project" method="post">
        {% csrf_token %}
        <label for="">Title</label>
        <input type="text" id="title" name="title" placeholder="Write title of the project" required>
        <br>
        <br>
        <br>

        <label for="">Description</label>
        <input type="text" id="description" name="description" placeholder="Write your description of the project" maxlength="100" size="100" required>
        <br>
        <br>
        <br>
      
        <div>
            <label for="members">Members:</label>
            {% for user in user_list %}
            <div class="form-check">
              <input
                type="checkbox"
                class="form-check-input"
                name="members"
                value="{{ user.id }}"
              />
              <label class="form-check-label"
                >{{ user.first_name }} {{ user.last_name }}</label
              >
              <select name="member_role_{{ user.id }}" class="form-select">
                <option value="1">Project Manager</option>
                <option value="2" selected>Project Member</option>
              </select>
            </div>
            {% endfor %}
          </div>
        
    <button type="submit">Create Project</button> 
    </form>
</div>
<div class="content-wrapper">
  {% block messages %} {% for message in messages %}
  <div
    class="alert alert-{{ message.tags }} alert-dismissible fade show"
    role="alert"
  >
    <strong style="color: #dc3545">Message:</strong> {{ message }}
    <button
      type="button"
      class="close"
      data-dismiss="alert"
      aria-label="close"
    >
      <span aria-hidden="true">&times;</span>
    </button>
    {% endfor %} {% endblock %}
</div>


{% endblock %}

issue_tracker/templates/dashboard/edit_profile.html
{% extends "dashboard/navigation.html" %}

{% block body %}

<h1>Edit Profile</h1>
<form action="/edit" method="post">
    {% csrf_token %}
    <label>First name</label>
    <input type="text" name="first_name" value="{{user.first_name}}"
      placeholder="Enter First name"
    />
    <br>
    <br>
    <label>Last name</label>
    <input type="text" name="last_name" value="{{user.last_name}}"
      placeholder="Enter Last name"
    />
    <br>
    <br>
    <button type="submit">Save Changes</button>
</form>

{% endblock %}

issue_tracker/templates/dashboard/edit_project.html
{% extends "dashboard/navigation.html" %}

{% block body %}

<h3>Update Project</h3>


  {% if users %}
  <form action="{% url 'projects:project_edit' project.id %}" method="post">
    {% csrf_token %}

    
      <label for="title">Title</label>
      <input
        type="text"
        id="title"
        name="title"
        placeholder="Enter the project title.."
        value="{{ project.title }}"
        readonly
        required
      />
<br>
<br>
      <label for="description">Description</label>
      <input
        type="text"
        id="description"
        name="description"
        class="form-control"
        placeholder="Enter your project description.."
        value="{{ project.description }}"
        required
      />
<br>
<br>
      <label for="members">Members:</label>
      {% for user in users %}
      <div class="form-check">
        <input
          type="checkbox"
          class="form-check-input"
          name="members[]"
          value="{{ user.id }}"
          {% if user in project.members.all %}
          checked
          {% endif %}
        />
        <label>{{ user.first_name }} {{ user.last_name }}</label>
        <select name="member_role_{{ user.id }}" class="form-select">
          <option value="2" {% if user in project.members.all and user.member.role == 2 %}selected{% endif %}>Project Member</option>
        </select>
      {% endfor %}
    <button type="submit" class="btn btn-primary create-button">
      Update Project
    </button>
  </form>
  {% else %}
  <p>
    You are not authorized to edit this project.
  </p>
  {% endif %}

{% endblock %}

issue_tracker/templates/dashboard/navigation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
   
    <title>Document</title>
</head>
<body>
    <navbar>
        <ul>
        <li><a href="{% url 'authentication:dashboard' %}">DASHBOARD</a></li>
        <li><a href="/projects">CREATE PROJECT</a></li>
        <li><a href="/signout">LOG OUT</a></li>
        <li><a href="/profile">PROFILE</a></li>
        </ul>
    </navbar>
    {% block body %}
        
    {% endblock %}
</body>
</html>

issue_tracker/templates/dashboard/show_profile.html
{% extends "dashboard/navigation.html" %}

{% block body %}

<p>Email: {{ user.email }}</p>
<p>First Name: {{ user.first_name }}</p>
<p>Last Name: {{ user.last_name }}</p>

<a href="/edit">Edit Profile</a>

{% endblock %}

issue_tracker/templates/dashboard/story_view.html
{% extends "dashboard/navigation.html" %}
{% block head %}
<style>

* {
  box-sizing: border-box;
}
    .dispaly{
        float: left;
        width: 50%;
        padding: 10px;
        height: 300px;
    }
    .row{
        content: "";
        display: table;
        clear: both;
    }
</style>

{% endblock %}
{% block body %}
    <h1>Story List</h1>
    <h2>{{ project.title }}</h2>
    <div class="row">
    <div class="display">    
    <h3 class>Scheduled Stories</h3>
    {% if scheduled_stories %} <ol>{% for story in scheduled_stories %}
        <li>
        <h4>Title: {{ story.title }}</h4>
        <p>Description: {{ story.description }}</p>
        <p>Estimated time:{{ story.estimated_time }}</p>
        <p>Assignee: {{ story.assignee }}</p>
        <p>Status: {{ story.get_status_display }}</p>
        
        <a
                href="{% url 'stories:update_story' project_id=project.id story_id=story.id %}"
                >Edit
        </a>
        <form
                action="{% url 'stories:delete_story' project_id=project.id story_id=story.id %}"
                method="post"
              >
              {% csrf_token %}
              <button type="submit">Delete</button>
        </form>
        </li>
    {% endfor %} </ol>{% else %}
   
    
    <p>No scheduled stories found</p>
    {% endif %}
    </div>
    <div class="display">
    <h3 class>Unscheduled Stories</h3>
    {% if unscheduled_stories %} <ol>{% for story in unscheduled_stories %}
        <li><h4>Title : {{ story.title }}</h4>
        <p>Description: {{ story.description }}</p>
        <p>Estimated time: {{ story.estimated_time }}</p>
        <p>Assignee: {{ story.assignee }}</p>
        <p>Status: {{ story.get_status_display }}</p>
        
        <a
                href="{% url 'stories:update_story' project_id=project.id story_id=story.id %}"
                
                >Edit
        </a>
        <form
                action="{% url 'stories:delete_story' project_id=project.id story_id=story.id %}"
                method="post"
              >
              {% csrf_token %}
              <button type="submit">Delete</button>
        </form>
        </li>
    {% endfor %}</ol> {% else %}
    <p>No unscheduled stories found</p>
    {% endif %}
    </div>
    </div>
{% endblock %}

issue_tracker/templates/dashboard/update_story.html
{% extends "dashboard/navigation.html" %}
{% block body %}
    <h1>Update Story</h1>
    {% if users %}
        <form action="" method="POST">
            {% csrf_token %} 
            {% if serializer_errors %}

            {% endif %}
            <label for="title">Title</label>
            <input type="text" id="title" name="title" value="{{ story.title }}" />
            <br>
            <br>
            <br>
            <label for="description">Description</label>
            <textarea id="description" name="description">{{ story.description }}</textarea>
            <br>
            <br>
            <br>

            <label for="estimate">Estimate</label>
            <input type="text" class="form-control" id="estimate" name="estimate" value="{{ story.estimated_time }}" />
            <br>
            <br>
            <label for="assignee">Assignee</label>
            <select  id="assignee" name="assignee">
            {% for user in users %}
            <option value="{{ user.id }}" {% if user.id == story.assignee.id %}selected{% endif %}>{{ user.first_name }}</option>
            {% endfor %}
            </select>
            <br>
            <br>
            <label for="status">Status</label>
            <select id="status" name="status">
              {% for choice in status_choices %}
              <option value="{{ choice.0 }}" {% if choice.0 == story.status %}selected{% endif %}>{{ choice.1 }}</option>
              {% endfor %}
            </select>
            <br>
            <br>
        <label for="is_scheduled">Scheduled/UnScheduled:</label>
          <select id="is_scheduled" name="is_scheduled">
            {% for choice in schedule_choices %}
            <option value="{{ choice.0 }}" {% if choice.0 == story.is_scheduled %}selected{% endif %}>{{ choice.1 }}</option>
            {% endfor %}
          </select>
          <br>
          <br>
          <button type="submit" class="btn btn-primary mt-3">Update Story</button>
        </form>
    {% else %}
    <p>You're not authorised to update this story</p>
    {% endif %}

{% endblock %}

issue_tracker/templates/dashboard/user.html
{% extends "dashboard/navigation.html" %}


{% block body %}
<div class="projects">
    <h2>Hello {{ fname }}</h2>
    <select name="language" id="filter-options">
        <option value="All">All</option>
        <option value="Member">Member</option>
        <option value="Owner">Owner</option>
        
    </select>
    <h1>Projects</h1>
    {% if projects %} {% for project in projects %}
    <h3>{{ project.title }}</h3>
    <P>{{ project.description }}</P>
     <a href="{% url 'stories:create_story' project_id=project.id %}">Add Story</a>
     <a href="{% url 'stories:stories_list' project_id=project.id %}">View Story</a>
     <a href="{% url 'projects:project_edit' project_id=project.id %}">Edit Project</a>   
    {% endfor %}
    {% else %}
    <h2>No projects assigned</h2>
    {% endif %}

</div>
<script>
    const filterOptions = document.getElementById("filter-options");
  
    filterOptions.addEventListener("change", () => {
      const selectedFilter = filterOptions.value;
      const url = `/dashboard/${selectedFilter}/`;
      window.location.href = url;
    });
  
    const currentFilter = "{{ filter_param }}";
    filterOptions.value = currentFilter;
  </script>
{% endblock %}